### ISSUE TITLE
Ellipsis is not working when using Truncate.at.end in multiline mode

### ISSUE THREAD

**Issue by Emasoft** [captain-miao/TopAlignedTextView#2]
With multiline this class is almost perfect! But there is still a bug: in multiline mode truncation seem broken now. Nothing happens when using:

textview.setEllipsize(android.text.TextUtils.TruncateAt.END);

It should truncate the last line with the Ellipsis char, like in this example:

![urzdo](https://cloud.githubusercontent.com/assets/713559/20455933/4ad2a03e-ae68-11e6-9546-6bb05ebc37d0.png)

I found this class that does the multiline ellipsizing in Textview, but unfortunately it doesn't preserve spannable text formatting:
https://github.com/triposo/barone/blob/master/src/com/triposo/barone/EllipsizingTextView.java

Can you fix this? Thank you!

**Comment by captain-miao** [comment]
I will try…

**Comment by Emasoft** [comment]
Any update on this?

**Comment by Emasoft** [comment]
If you are having trouble, here is another example: https://github.com/dinuscxj/EllipsizeTextView

**Comment by captain-miao** [comment]
@Emasoft Thank you, I commit a beta(has a bug).

**Comment by captain-miao** [comment]
It's from example: https://github.com/dinuscxj/EllipsizeTextView, just show "..."

**Comment by Emasoft** [comment]
Thanks! Can you fix the bug? 

P.S.
Showing "..." is not enough. As you can see in the pic I posted, a **"More ▼"** label should be available to expand the full text on touch (or alternatively rising an event). The unicode for the big black arrow down is this: U+025BC

**Comment by captain-miao** [comment]
need more time~ 😃

**Comment by captain-miao** [comment]
It's working now.

**Comment by Emasoft** [comment]
Thank you!
