### ISSUE TITLE
Problem with multiline textview

### ISSUE THREAD

**Issue by bahaa-sharqawe** [captain-miao/TopAlignedTextView#3]
Not working with multiline textview since the text is cut when the textview width exceeded the parent view width.

In my case, the parent view is  framelayout.
Thanks...

**Comment by captain-miao** [comment]
can you give me  the layout?

**Comment by captain-miao** [comment]
I fixed it, please check it.

**Comment by bahaa-sharqawe** [comment]
@captain-miao OK.
