### ISSUE TITLE
反馈TopAlignedTextView BUG

### ISSUE THREAD

**Issue by tcqq** [captain-miao/TopAlignedTextView#4]
检查图片中的字母`n` 
![image](https://user-images.githubusercontent.com/10644057/37773034-714c9ab4-2e17-11e8-834a-c267b3669f2f.png)

**Comment by captain-miao** [comment]
你的这个布局文件发出来看看

**Comment by tcqq** [comment]
对不起，以前的布局代码发生了变化。 我试图重现这个问题，但不幸的是这个问题没有再次发生。
